version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend_c
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true

  mongo:
    image: mongo:latest
    container_name: mongo_c
    ports:
      - '27017:27017'
